name: Build Blender (Tariq Mirror PR)

on:
  workflow_dispatch:  # 允许手动点击运行

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: 检出 Blender 官方源码
        uses: actions/checkout@v4
        with:
          repository: blender/blender
          fetch-depth: 0

      - name: 获取 Tariq 分支代码
        run: |
          git fetch origin pull/142698/head:pr-142698
          git checkout pr-142698

      - name: 安装依赖
        run: |
          choco install ninja cmake git -y
          git submodule update --init --recursive

      - name: 创建构建目录
        run: mkdir build

      - name: CMake 配置
        working-directory: build
        run: cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release

      - name: 编译 Blender
        working-directory: build
        run: ninja

      - name: 打包构建结果
        run: |
          mkdir output
          copy build\bin\Release\blender.exe output\
          copy build\bin\Release\*.dll output\
          Compress-Archive -Path output\* -DestinationPath blender_tariq_win.zip

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: blender_tariq_win
          path: blender_tariq_win.zip
