name: Build Blender from Gerrit PR D142698

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: 安装依赖
        run: |
          choco install ninja cmake git -y

      - name: 克隆 Blender 官方仓库（官方 git.blender.org）
        run: git clone --depth=1 https://git.blender.org/blender.git

      - name: 拉取 Gerrit PR D142698 代码
        working-directory: blender
        run: |
          git fetch origin refs/changes/98/142698/1 && git checkout FETCH_HEAD

      - name: 初始化子模块
        working-directory: blender
        run: git submodule update --init --recursive

      - name: 创建构建目录
        run: mkdir build

      - name: CMake 配置 Blender
        working-directory: build
        run: cmake ../blender -G "Ninja" -DCMAKE_BUILD_TYPE=Release

      - name: Ninja 编译
        working-directory: build
        run: ninja

      - name: 打包 exe 和 dll
        run: |
          mkdir output
          copy build\bin\Release\blender.exe output\
          copy build\bin\Release\*.dll output\
          Compress-Archive -Path output\* -DestinationPath blender_d142698_win.zip

      - name: 上传构建产物
        uses: actions/upload-artifact@v3
        with:
          name: blender_d142698_win
          path: blender_d142698_win.zip
