name: 编译Windows 10版Blender（多轴镜像测试）
on:
  workflow_dispatch:  # 允许手动触发

jobs:
  build-windows:
    runs-on: windows-latest  # 使用Windows系统编译
    steps:
      - name: 拉取代码（指定目标分支）
        uses: actions/checkout@v4
        with:
          ref: Tariq-13/blender:gsoc-2025-edit-mesh-mirroring-hideselected  # 替换为Tariq的PR分支名
          submodules: recursive  # 拉取所有子模块

      - name: 安装依赖（Visual Studio工具链）
        uses: ilammy/msvc-dev-cmd@v1  # 配置Visual Studio编译环境

      - name: 配置CMake（生成Visual Studio项目）
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release
        shell: cmd  # 使用Windows命令提示符

      - name: 编译Blender（Release模式）
        run: |
          cd build
          msbuild Blender.sln /p:Configuration=Release /p:Platform=x64 /m
        shell: cmd  # 用msbuild编译（Visual Studio的命令行工具）

      - name: 上传Windows编译产物
        uses: actions/upload-artifact@v3
        with:
          name: blender-windows-build
          path: build/bin/Release/  # Windows下的Release版本输出路径
    
