name: Build Tariq Blender

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: 安装依赖
        run: |
          choco install ninja cmake git -y

      - name: 克隆 Tariq 仓库
        run: git clone --depth=1 https://projects.blender.org/Tariq-13/blender.git

      - name: 初始化子模块
        working-directory: blender
        run: git submodule update --init --recursive

      - name: 创建构建目录
        run: mkdir build

      - name: CMake 配置
        working-directory: build
        run: cmake ../blender -G "Ninja" -DCMAKE_BUILD_TYPE=Release

      - name: 编译 Blender
        working-directory: build
        run: ninja

      - name: 打包 Blender
        run: |
          mkdir output
          copy build\bin\Release\blender.exe output\
          copy build\bin\Release\*.dll output\
          Compress-Archive -Path output\* -DestinationPath blender_tariq_win.zip

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: blender_tariq_win
          path: blender_tariq_win.zip
